package jp.systemengineeya.bookreview.api.entity;

public class BookImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.book_id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.s3_key
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    private String s3Key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.id
     *
     * @return the value of book_image.id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.id
     *
     * @param id the value for book_image.id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.book_id
     *
     * @return the value of book_image.book_id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.book_id
     *
     * @param bookId the value for book_image.book_id
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.s3_key
     *
     * @return the value of book_image.s3_key
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.s3_key
     *
     * @param s3Key the value for book_image.s3_key
     *
     * @mbg.generated Thu May 21 23:49:10 JST 2026
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }
}