package jp.systemengineeya.bookreview.api.entity;

public class BookImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.book_id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_image.extension
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    private String extension;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.id
     *
     * @return the value of book_image.id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.id
     *
     * @param id the value for book_image.id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.book_id
     *
     * @return the value of book_image.book_id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.book_id
     *
     * @param bookId the value for book_image.book_id
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_image.extension
     *
     * @return the value of book_image.extension
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_image.extension
     *
     * @param extension the value for book_image.extension
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }
}