package jp.systemengineeya.bookreview.api.entity;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.book_id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    private Long bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.rating
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    private Integer rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.book_id
     *
     * @return the value of review.book_id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.book_id
     *
     * @param bookId the value for review.book_id
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.rating
     *
     * @return the value of review.rating
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.rating
     *
     * @param rating the value for review.rating
     *
     * @mbg.generated Sat May 02 15:17:49 JST 2026
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }
}