spring:
  application:
    name: book-review-api
  datasource:
    url: jdbc:postgresql://localhost:5432/book_review
    username: postgres
    password: password
  flyway:
    enabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml