package jp.systemengineeya.bookreview.api.mapper.mybatis;

import java.util.List;
import jp.systemengineeya.bookreview.api.entity.BookImage;
import jp.systemengineeya.bookreview.api.entity.BookImageExample;
import org.apache.ibatis.annotations.Param;

public interface BookImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    long countByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int deleteByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int insert(BookImage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int insertSelective(BookImage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    List<BookImage> selectByExample(BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    BookImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int updateByExampleSelective(@Param("row") BookImage row, @Param("example") BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int updateByExample(@Param("row") BookImage row, @Param("example") BookImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int updateByPrimaryKeySelective(BookImage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_image
     *
     * @mbg.generated Sun May 10 01:46:02 JST 2026
     */
    int updateByPrimaryKey(BookImage row);
}