package jp.systemengineeya.bookreview.api.mapper.mybatis;

import java.util.List;
import jp.systemengineeya.bookreview.api.entity.Review;
import jp.systemengineeya.bookreview.api.entity.ReviewExample;
import org.apache.ibatis.annotations.Param;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    long countByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int deleteByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int insert(Review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int insertSelective(Review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    List<Review> selectByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    Review selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int updateByExampleSelective(@Param("row") Review row, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int updateByExample(@Param("row") Review row, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int updateByPrimaryKeySelective(Review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Sun May 03 17:36:36 JST 2026
     */
    int updateByPrimaryKey(Review row);
}