openapi: 3.0.3
info:
  title: 書籍レビューAPI
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /books:
    $ref: './paths/books.yml#/books'
  /books/{bookId}:
    $ref: './paths/books.yml#/bookById'
  /books/{bookId}/reviews:
    $ref: './paths/reviews.yml#/reviews'
  /books/{bookId}/reviews/{reviewId}:
    $ref: './paths/reviews.yml#/reviewById'
  /books/{bookId}/images:
    post:
      tags:
      - book-image-controller
      operationId: upload
      parameters:
      - name: bookId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
              required:
              - image
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookImageResponse"
  /books/{bookId}/images/{imageId}:
    delete:
      tags:
      - book-image-controller
      operationId: delete
      parameters:
      - name: bookId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: imageId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    BookRequest:
      $ref: './schemas/book.yml#/BookRequest'
    BookResponse:
      $ref: './schemas/book.yml#/BookResponse'
    BookImageResponse:
      $ref: './schemas/book-image.yml#/BookImageResponse'
    ReviewRequest:
      $ref: './schemas/review.yml#/ReviewRequest'
    ReviewResponse:
      $ref: './schemas/review.yml#/ReviewResponse'
